# config.mk
#
# Product-specific compile-time definitions.
#
TARGET_BOARD_PLATFORM := exynos4
TARGET_SOC := exynos4x12

CPU_EXYNOS4212 := false
CPU_EXYNOS4412 := true

# CPU options
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a9
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_ARCH_VARIANT_CPU := cortex-a9
ARCH_ARM_HAVE_NEON := true

#for recovery
TARGET_PROVIDES_INIT_TARGET_RC := true
TARGET_NO_BOOTLOADER          := true
TARGET_NO_KERNEL              := true
TARGET_NO_RADIOIMAGE          := true
TARGET_BOOTLOADER_BOARD_NAME  := smdk4x12
TARGET_RECOVERY_PIXEL_FORMAT  := "BGRA_8888"

BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_I2S_AUDIO := true
BOARD_USES_PCM_AUDIO := false
BOARD_USES_SPDIF_AUDIO := false
BOARD_HAVE_BLUETOOTH := false

# ULP Audio
USE_ULP_AUDIO := false

# ALP Audio
BOARD_USE_ALP_AUDIO := true

# SEC Camera
USE_SEC_CAMERA := false
CAMERA_USE_DIGITALZOOM := true
BOARD_USE_S5K3H2 := true
BOARD_USE_USBCAM := false
BOARD_USE_S5K4H5 := false

# Enable JIT
WITH_JIT := true

BOARD_HAS_TWOSTORAGES := true
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 524288000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 14994636800
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_USES_HGL := true
BOARD_NO_32BPP := true

# HDMI
BOARD_USES_HDMI_SUBTITLES := true
BOARD_USES_HDMI := true
BOARD_HDMI_STD := STD_720P
BOARD_HDMI_DDC_CH := DDC_CH_I2C_2
BOARD_USES_FIMGAPI := true
BOARD_USES_EDID := false
BOARD_USES_HDMI_JUMPER := true

BOARD_USE_SAMSUNG_COLORFORMAT := true
BOARD_FIX_NATIVE_COLOR_FORMAT := true
BOARD_NONBLOCK_MODE_PROCESS := true
BOARD_USE_STOREMETADATA := true
BOARD_USE_METADATABUFFERTYPE := true
BOARD_USES_MFC_FPS := false
BOARD_USE_S3D_SUPPORT := false
BOARD_USE_CSC_FIMC := false
BOARD_USE_H264_PREPEND_SPS_PPS := true

BOARD_USES_HIGH_RESOLUTION_LCD := true

# Enable V4L2 & ION
BOARD_USE_V4L2 := false
BOARD_USE_V4L2_ION := false
BOARD_NO_OVERLAY := false

SCREEN_WIDTH := 1080
SCREEN_HEIGHT := 720
DEFAULT_FB_NUM := 0
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3

USE_OPENGL_RENDERER := true

#for led_torch
USE_LED_TORCH := true

WIFI_RTL8188 := true
ifeq ($(WIFI_RTL8188),true)
  BOARD_WIFI_VENDOR                 := realtek
  WPA_SUPPLICANT_VERSION            := VER_0_8_X
  BOARD_WPA_SUPPLICANT_DRIVER       := NL80211
  BOARD_WPA_SUPPLICANT_PRIVATE_LIB  := lib_driver_cmd_rtl
  BOARD_HOSTAPD_DRIVER              := NL80211
  BOARD_HOSTAPD_PRIVATE_LIB         := lib_driver_cmd_rtl

  BOARD_WLAN_DEVICE                 := rtl8192cu
  WIFI_DRIVER_MODULE_NAME           := 8192cu
  WIFI_DRIVER_MODULE_PATH           := "8192cu.ko"
  WIFI_DRIVER_MODULE_PATH1          := "/system/lib/modules/8192cu.ko"
  WIFI_DRIVER_MODULE_PATH2          := "/system/lib/modules/8188eu.ko"
  WIFI_DRIVER_MODULE_ARG            := ""
  WIFI_FIRMWARE_LOADER              := ""
  WIFI_DRIVER_FW_PATH_STA           := ""
  WIFI_DRIVER_FW_PATH_AP            := ""
  WIFI_DRIVER_FW_PATH_P2P           := ""
  WIFI_DRIVER_FW_PATH_PARAM         := ""
endif
